///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddRestaurantListRequest {
/*
{
  "id": "123456",
  "place_name": "얌스택 식당",
  "category_name": "음식점 > 한식 > 분식",
  "category_group_code": "",
  "category_group_name": "",
  "phone": "02-123-1234",
  "address_name": "서울 동작구 상도동 123-123",
  "road_address_name": "서울 동작구 성대로123길 123",
  "x": "127.05902969025047",
  "y": "37.51207412593136",
  "place_url": "http://place.map.kakao.com/26338954",
  "foods": [
    "제육볶음"
  ],
  "tags": [
    "미슐랭"
  ],
  "memo": "테스트 식당"
}
*/

  String? id;
  String? placeName;
  String? categoryName;
  String? categoryGroupCode;
  String? categoryGroupName;
  String? phone;
  String? addressName;
  String? roadAddressName;
  String? x;
  String? y;
  String? placeUrl;
  List<String?>? foods;
  List<String?>? tags;
  String? memo;

  AddRestaurantListRequest({
    this.id,
    this.placeName,
    this.categoryName,
    this.categoryGroupCode,
    this.categoryGroupName,
    this.phone,
    this.addressName,
    this.roadAddressName,
    this.x,
    this.y,
    this.placeUrl,
    this.foods,
    this.tags,
    this.memo,
  });
  AddRestaurantListRequest.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    placeName = json["place_name"]?.toString();
    categoryName = json["category_name"]?.toString();
    categoryGroupCode = json["category_group_code"]?.toString();
    categoryGroupName = json["category_group_name"]?.toString();
    phone = json["phone"]?.toString();
    addressName = json["address_name"]?.toString();
    roadAddressName = json["road_address_name"]?.toString();
    x = json["x"]?.toString();
    y = json["y"]?.toString();
    placeUrl = json["place_url"]?.toString();
    if (json["foods"] != null) {
      final v = json["foods"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      foods = arr0;
    }
    if (json["tags"] != null) {
      final v = json["tags"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    memo = json["memo"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["place_name"] = placeName;
    data["category_name"] = categoryName;
    data["category_group_code"] = categoryGroupCode;
    data["category_group_name"] = categoryGroupName;
    data["phone"] = phone;
    data["address_name"] = addressName;
    data["road_address_name"] = roadAddressName;
    data["x"] = x;
    data["y"] = y;
    data["place_url"] = placeUrl;
    if (foods != null) {
      final v = foods;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["foods"] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["tags"] = arr0;
    }
    data["memo"] = memo;
    return data;
  }
}
