///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VisitYamRequest {
/*
{
  "id": 123,
  "reVisit": true
}
*/

  int? id;
  bool? reVisit;

  VisitYamRequest({
    this.id,
    this.reVisit,
  });
  VisitYamRequest.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    reVisit = json["reVisit"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["reVisit"] = reVisit;
    return data;
  }
}