///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AccountResponse {
/*
{
  "id": 0,
  "email": "test@aaa.bbb",
  "name": "test",
  "role": "USER",
  "lastLoginDate": null,
  "pwChangedDate": null,
  "emailChecked": false
}
*/

  int? id;
  String? email;
  String? name;
  String? role;
  String? lastLoginDate;
  String? pwChangedDate;
  bool? emailChecked;

  AccountResponse({
    this.id,
    this.email,
    this.name,
    this.role,
    this.lastLoginDate,
    this.pwChangedDate,
    this.emailChecked,
  });
  AccountResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    email = json["email"]?.toString();
    name = json["name"]?.toString();
    role = json["role"]?.toString();
    lastLoginDate = json["lastLoginDate"]?.toString();
    pwChangedDate = json["pwChangedDate"]?.toString();
    emailChecked = json["emailChecked"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["email"] = email;
    data["name"] = name;
    data["role"] = role;
    data["lastLoginDate"] = lastLoginDate;
    data["pwChangedDate"] = pwChangedDate;
    data["emailChecked"] = emailChecked;
    return data;
  }
}
