///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PasswdCheckResponse {
/*
{
  "id": 0,
  "email": "test@aaa.bbb",
  "name": "test",
  "role": "USER",
  "lastLoginDate": null,
  "pwChangedDate": null,
  "emailChecked": false
}
*/

  String? message;
  String? code;
  int? status;

  PasswdCheckResponse({
    this.message,
    this.code,
    this.status,
  });
  PasswdCheckResponse.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    code = json["code"]?.toString();
    status = json["status"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    data["code"] = code;
    data["status"] = status;
    return data;
  }
}
