///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RestaurantResponseSort {
/*
{
  "sorted": true,
  "unsorted": false,
  "empty": false
}
*/

  bool? sorted;
  bool? unsorted;
  bool? empty;

  RestaurantResponseSort({
    this.sorted,
    this.unsorted,
    this.empty,
  });
  RestaurantResponseSort.fromJson(Map<String, dynamic> json) {
    sorted = json["sorted"];
    unsorted = json["unsorted"];
    empty = json["empty"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["sorted"] = sorted;
    data["unsorted"] = unsorted;
    data["empty"] = empty;
    return data;
  }
}

class RestaurantResponsePageableSort {
/*
{
  "sorted": true,
  "unsorted": false,
  "empty": false
}
*/

  bool? sorted;
  bool? unsorted;
  bool? empty;

  RestaurantResponsePageableSort({
    this.sorted,
    this.unsorted,
    this.empty,
  });
  RestaurantResponsePageableSort.fromJson(Map<String, dynamic> json) {
    sorted = json["sorted"];
    unsorted = json["unsorted"];
    empty = json["empty"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["sorted"] = sorted;
    data["unsorted"] = unsorted;
    data["empty"] = empty;
    return data;
  }
}

class RestaurantResponsePageable {
/*
{
  "sort": {
    "sorted": true,
    "unsorted": false,
    "empty": false
  },
  "pageNumber": 0,
  "pageSize": 5,
  "offset": 0,
  "paged": true,
  "unpaged": false
}
*/

  RestaurantResponsePageableSort? sort;
  int? pageNumber;
  int? pageSize;
  int? offset;
  bool? paged;
  bool? unpaged;

  RestaurantResponsePageable({
    this.sort,
    this.pageNumber,
    this.pageSize,
    this.offset,
    this.paged,
    this.unpaged,
  });
  RestaurantResponsePageable.fromJson(Map<String, dynamic> json) {
    sort = (json["sort"] != null) ? RestaurantResponsePageableSort.fromJson(json["sort"]) : null;
    pageNumber = json["pageNumber"]?.toInt();
    pageSize = json["pageSize"]?.toInt();
    offset = json["offset"]?.toInt();
    paged = json["paged"];
    unpaged = json["unpaged"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (sort != null) {
      data["sort"] = sort!.toJson();
    }
    data["pageNumber"] = pageNumber;
    data["pageSize"] = pageSize;
    data["offset"] = offset;
    data["paged"] = paged;
    data["unpaged"] = unpaged;
    return data;
  }
}

class RestaurantResponseContentReviews {
/*
{
  "id": 100,
  "visitTime": "2021-04-05",
  "genTime": "2021-07-14",
  "imagePath": "https://aws.s3.com/image100.jpg",
  "comment": "가성비 훌륭",
  "company": "ALONE",
  "mealTime": null,
  "likeCount": 10,
  "nickName": "얌얌박사",
  "restaurantName": "식당100",
  "iliked": false,
  "shared": true
}
*/

  int? id;
  String? visitTime;
  String? genTime;
  String? imagePath;
  String? comment;
  String? company;
  String? mealTime;
  int? likeCount;
  String? nickName;
  String? restaurantName;
  bool? iliked;
  bool? shared;

  RestaurantResponseContentReviews({
    this.id,
    this.visitTime,
    this.genTime,
    this.imagePath,
    this.comment,
    this.company,
    this.mealTime,
    this.likeCount,
    this.nickName,
    this.restaurantName,
    this.iliked,
    this.shared,
  });
  RestaurantResponseContentReviews.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    visitTime = json["visitTime"]?.toString();
    genTime = json["genTime"]?.toString();
    imagePath = json["imagePath"]?.toString();
    comment = json["comment"]?.toString();
    company = json["company"]?.toString();
    mealTime = json["mealTime"]?.toString();
    likeCount = json["likeCount"]?.toInt();
    nickName = json["nickName"]?.toString();
    restaurantName = json["restaurantName"]?.toString();
    iliked = json["iliked"];
    shared = json["shared"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["visitTime"] = visitTime;
    data["genTime"] = genTime;
    data["imagePath"] = imagePath;
    data["comment"] = comment;
    data["company"] = company;
    data["mealTime"] = mealTime;
    data["likeCount"] = likeCount;
    data["nickName"] = nickName;
    data["restaurantName"] = restaurantName;
    data["iliked"] = iliked;
    data["shared"] = shared;
    return data;
  }
}

class RestaurantResponseContentRestaurant {
/*
{
  "id": 123,
  "apiId": "123456",
  "name": "식당100",
  "addName": "서울 동작구 상도동100-155",
  "roadAddName": "서울 동작구 성대로100길 155",
  "region1depth": "서울",
  "region2depth": "동작구",
  "region3depth": "상도동",
  "x": "127.100",
  "y": "37.100",
  "category1depth": "음식점",
  "category2depth": "한식",
  "closedCount": 0
}
*/

  int? id;
  String? apiId;
  String? name;
  String? addName;
  String? roadAddName;
  String? region1depth;
  String? region2depth;
  String? region3depth;
  String? x;
  String? y;
  String? category1depth;
  String? category2depth;
  int? closedCount;

  RestaurantResponseContentRestaurant({
    this.id,
    this.apiId,
    this.name,
    this.addName,
    this.roadAddName,
    this.region1depth,
    this.region2depth,
    this.region3depth,
    this.x,
    this.y,
    this.category1depth,
    this.category2depth,
    this.closedCount,
  });
  RestaurantResponseContentRestaurant.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    apiId = json["apiId"]?.toString();
    name = json["name"]?.toString();
    addName = json["addName"]?.toString();
    roadAddName = json["roadAddName"]?.toString();
    region1depth = json["region1depth"]?.toString();
    region2depth = json["region2depth"]?.toString();
    region3depth = json["region3depth"]?.toString();
    x = json["x"]?.toString();
    y = json["y"]?.toString();
    category1depth = json["category1depth"]?.toString();
    category2depth = json["category2depth"]?.toString();
    closedCount = json["closedCount"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["apiId"] = apiId;
    data["name"] = name;
    data["addName"] = addName;
    data["roadAddName"] = roadAddName;
    data["region1depth"] = region1depth;
    data["region2depth"] = region2depth;
    data["region3depth"] = region3depth;
    data["x"] = x;
    data["y"] = y;
    data["category1depth"] = category1depth;
    data["category2depth"] = category2depth;
    data["closedCount"] = closedCount;
    return data;
  }
}

class RestaurantResponseContent {
/*
{
  "restaurant": {
    "id": 123,
    "apiId": "123456",
    "name": "식당100",
    "addName": "서울 동작구 상도동100-155",
    "roadAddName": "서울 동작구 성대로100길 155",
    "region1depth": "서울",
    "region2depth": "동작구",
    "region3depth": "상도동",
    "x": "127.100",
    "y": "37.100",
    "category1depth": "음식점",
    "category2depth": "한식",
    "closedCount": 0
  },
  "dist": 100,
  "yamPick": 56,
  "visitNum": 30,
  "recommend": 25,
  "reviewNum": 1,
  "company": "ALONE",
  "foods": [
    "계란말이"
  ],
  "tags": [
    "혼밥"
  ],
  "reviews": [
    {
      "id": 100,
      "visitTime": "2021-04-05",
      "genTime": "2021-07-14",
      "imagePath": "https://aws.s3.com/image100.jpg",
      "comment": "가성비 훌륭",
      "company": "ALONE",
      "mealTime": null,
      "likeCount": 10,
      "nickName": "얌얌박사",
      "restaurantName": "식당100",
      "iliked": false,
      "shared": true
    }
  ]
}
*/

  RestaurantResponseContentRestaurant? restaurant;
  int? dist;
  int? yamPick;
  int? visitNum;
  int? recommend;
  int? reviewNum;
  String? company;
  List<String?>? foods;
  List<String?>? tags;
  List<RestaurantResponseContentReviews?>? reviews;

  RestaurantResponseContent({
    this.restaurant,
    this.dist,
    this.yamPick,
    this.visitNum,
    this.recommend,
    this.reviewNum,
    this.company,
    this.foods,
    this.tags,
    this.reviews,
  });
  RestaurantResponseContent.fromJson(Map<String, dynamic> json) {
    restaurant = (json["restaurant"] != null) ? RestaurantResponseContentRestaurant.fromJson(json["restaurant"]) : null;
    dist = json["dist"]?.toInt();
    yamPick = json["yamPick"]?.toInt();
    visitNum = json["visitNum"]?.toInt();
    recommend = json["recommend"]?.toInt();
    reviewNum = json["reviewNum"]?.toInt();
    company = json["company"]?.toString();
    if (json["foods"] != null) {
      final v = json["foods"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      foods = arr0;
    }
    if (json["tags"] != null) {
      final v = json["tags"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    if (json["reviews"] != null) {
      final v = json["reviews"];
      final arr0 = <RestaurantResponseContentReviews>[];
      v.forEach((v) {
        arr0.add(RestaurantResponseContentReviews.fromJson(v));
      });
      reviews = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (restaurant != null) {
      data["restaurant"] = restaurant!.toJson();
    }
    data["dist"] = dist;
    data["yamPick"] = yamPick;
    data["visitNum"] = visitNum;
    data["recommend"] = recommend;
    data["reviewNum"] = reviewNum;
    data["company"] = company;
    if (foods != null) {
      final v = foods;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["foods"] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["tags"] = arr0;
    }
    if (reviews != null) {
      final v = reviews;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["reviews"] = arr0;
    }
    return data;
  }
}

class RestaurantResponse {
/*
{
  "content": [
    {
      "restaurant": {
        "id": 123,
        "apiId": "123456",
        "name": "식당100",
        "addName": "서울 동작구 상도동100-155",
        "roadAddName": "서울 동작구 성대로100길 155",
        "region1depth": "서울",
        "region2depth": "동작구",
        "region3depth": "상도동",
        "x": "127.100",
        "y": "37.100",
        "category1depth": "음식점",
        "category2depth": "한식",
        "closedCount": 0
      },
      "dist": 100,
      "yamPick": 56,
      "visitNum": 30,
      "recommend": 25,
      "reviewNum": 1,
      "company": "ALONE",
      "foods": [
        "계란말이"
      ],
      "tags": [
        "혼밥"
      ],
      "reviews": [
        {
          "id": 100,
          "visitTime": "2021-04-05",
          "genTime": "2021-07-14",
          "imagePath": "https://aws.s3.com/image100.jpg",
          "comment": "가성비 훌륭",
          "company": "ALONE",
          "mealTime": null,
          "likeCount": 10,
          "nickName": "얌얌박사",
          "restaurantName": "식당100",
          "iliked": false,
          "shared": true
        }
      ]
    }
  ],
  "pageable": {
    "sort": {
      "sorted": true,
      "unsorted": false,
      "empty": false
    },
    "pageNumber": 0,
    "pageSize": 5,
    "offset": 0,
    "paged": true,
    "unpaged": false
  },
  "totalPages": 2,
  "totalElements": 10,
  "last": false,
  "first": true,
  "numberOfElements": 5,
  "sort": {
    "sorted": true,
    "unsorted": false,
    "empty": false
  },
  "size": 5,
  "number": 0,
  "empty": false
}
*/

  List<RestaurantResponseContent?>? content;
  RestaurantResponsePageable? pageable;
  int? totalPages;
  int? totalElements;
  bool? last;
  bool? first;
  int? numberOfElements;
  RestaurantResponseSort? sort;
  int? size;
  int? number;
  bool? empty;

  RestaurantResponse({
    this.content,
    this.pageable,
    this.totalPages,
    this.totalElements,
    this.last,
    this.first,
    this.numberOfElements,
    this.sort,
    this.size,
    this.number,
    this.empty,
  });
  RestaurantResponse.fromJson(Map<String, dynamic> json) {
    if (json["content"] != null) {
      final v = json["content"];
      final arr0 = <RestaurantResponseContent>[];
      v.forEach((v) {
        arr0.add(RestaurantResponseContent.fromJson(v));
      });
      content = arr0;
    }
    pageable = (json["pageable"] != null) ? RestaurantResponsePageable.fromJson(json["pageable"]) : null;
    totalPages = json["totalPages"]?.toInt();
    totalElements = json["totalElements"]?.toInt();
    last = json["last"];
    first = json["first"];
    numberOfElements = json["numberOfElements"]?.toInt();
    sort = (json["sort"] != null) ? RestaurantResponseSort.fromJson(json["sort"]) : null;
    size = json["size"]?.toInt();
    number = json["number"]?.toInt();
    empty = json["empty"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (content != null) {
      final v = content;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["content"] = arr0;
    }
    if (pageable != null) {
      data["pageable"] = pageable!.toJson();
    }
    data["totalPages"] = totalPages;
    data["totalElements"] = totalElements;
    data["last"] = last;
    data["first"] = first;
    data["numberOfElements"] = numberOfElements;
    if (sort != null) {
      data["sort"] = sort!.toJson();
    }
    data["size"] = size;
    data["number"] = number;
    data["empty"] = empty;
    return data;
  }
}
