///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YamEditReponseTags {
/*
{
  "name": "추가태그"
}
*/

  String? name;

  YamEditReponseTags({
    this.name,
  });
  YamEditReponseTags.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    return data;
  }
}

class YamEditReponseFoods {
/*
{
  "name": "추가음식"
}
*/

  String? name;

  YamEditReponseFoods({
    this.name,
  });
  YamEditReponseFoods.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    return data;
  }
}

class YamEditReponseRestaurant {
/*
{
  "id": 456,
  "apiId": "123456",
  "name": "얌스택 식당",
  "addName": "서울 동작구 상도동 123-123",
  "roadAddName": "서울 동작구 성대로123길 123",
  "region1depth": "서울",
  "region2depth": "동작구",
  "region3depth": "상도동",
  "x": "127.05902969025047",
  "y": "37.51207412593136",
  "category1depth": "음식점",
  "category2depth": "한식",
  "closedCount": 0
}
*/

  int? id;
  String? apiId;
  String? name;
  String? addName;
  String? roadAddName;
  String? region1depth;
  String? region2depth;
  String? region3depth;
  String? x;
  String? y;
  String? category1depth;
  String? category2depth;
  int? closedCount;

  YamEditReponseRestaurant({
    this.id,
    this.apiId,
    this.name,
    this.addName,
    this.roadAddName,
    this.region1depth,
    this.region2depth,
    this.region3depth,
    this.x,
    this.y,
    this.category1depth,
    this.category2depth,
    this.closedCount,
  });
  YamEditReponseRestaurant.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    apiId = json["apiId"]?.toString();
    name = json["name"]?.toString();
    addName = json["addName"]?.toString();
    roadAddName = json["roadAddName"]?.toString();
    region1depth = json["region1depth"]?.toString();
    region2depth = json["region2depth"]?.toString();
    region3depth = json["region3depth"]?.toString();
    x = json["x"]?.toString();
    y = json["y"]?.toString();
    category1depth = json["category1depth"]?.toString();
    category2depth = json["category2depth"]?.toString();
    closedCount = json["closedCount"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["apiId"] = apiId;
    data["name"] = name;
    data["addName"] = addName;
    data["roadAddName"] = roadAddName;
    data["region1depth"] = region1depth;
    data["region2depth"] = region2depth;
    data["region3depth"] = region3depth;
    data["x"] = x;
    data["y"] = y;
    data["category1depth"] = category1depth;
    data["category2depth"] = category2depth;
    data["closedCount"] = closedCount;
    return data;
  }
}

class YamEditReponse {
/*
{
  "id": 123,
  "genTime": "2021-07-16",
  "competeTime": null,
  "restaurant": {
    "id": 456,
    "apiId": "123456",
    "name": "얌스택 식당",
    "addName": "서울 동작구 상도동 123-123",
    "roadAddName": "서울 동작구 성대로123길 123",
    "region1depth": "서울",
    "region2depth": "동작구",
    "region3depth": "상도동",
    "x": "127.05902969025047",
    "y": "37.51207412593136",
    "category1depth": "음식점",
    "category2depth": "한식",
    "closedCount": 0
  },
  "foods": [
    {
      "name": "추가음식"
    }
  ],
  "tags": [
    {
      "name": "추가태그"
    }
  ],
  "memo": "얌 수정",
  "review": null,
  "good": true
}
*/

  int? id;
  String? genTime;
  String? competeTime;
  YamEditReponseRestaurant? restaurant;
  List<YamEditReponseFoods?>? foods;
  List<YamEditReponseTags?>? tags;
  String? memo;
  String? review;
  bool? good;

  YamEditReponse({
    this.id,
    this.genTime,
    this.competeTime,
    this.restaurant,
    this.foods,
    this.tags,
    this.memo,
    this.review,
    this.good,
  });
  YamEditReponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    genTime = json["genTime"]?.toString();
    competeTime = json["competeTime"]?.toString();
    restaurant = (json["restaurant"] != null) ? YamEditReponseRestaurant.fromJson(json["restaurant"]) : null;
    if (json["foods"] != null) {
      final v = json["foods"];
      final arr0 = <YamEditReponseFoods>[];
      v.forEach((v) {
        arr0.add(YamEditReponseFoods.fromJson(v));
      });
      foods = arr0;
    }
    if (json["tags"] != null) {
      final v = json["tags"];
      final arr0 = <YamEditReponseTags>[];
      v.forEach((v) {
        arr0.add(YamEditReponseTags.fromJson(v));
      });
      tags = arr0;
    }
    memo = json["memo"]?.toString();
    review = json["review"]?.toString();
    good = json["good"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["genTime"] = genTime;
    data["competeTime"] = competeTime;
    if (restaurant != null) {
      data["restaurant"] = restaurant!.toJson();
    }
    if (foods != null) {
      final v = foods;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["foods"] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["tags"] = arr0;
    }
    data["memo"] = memo;
    data["review"] = review;
    data["good"] = good;
    return data;
  }
}
